[0;31mTypeError: test/samples/compiler/function_given_too_many_args.py:5:3
[0m[0mcallable `fn` takes 2 arguments but 3 were given[0m
[0m  5| fn(1, 2, 3)
[0m
exitcode=1