[0;31mTypeError: test/errors/function/too_many_args2.np:5:3
[0m[0mcallable `fn` accepts 1 arguments but 2 were given[0m
[0m  5| fn(1, 2)
[0m
exitcode=1